name: nirapod_ai
description: Nirapod AI mobile cybersecurity protection application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.5.0
  camera: ^0.12.0+2
  image_picker: ^1.1.2
  mobile_scanner: ^7.4.0
  google_mlkit_text_recognition: ^0.15.0
  shared_preferences: ^2.5.3
  image: ^4.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
